### PR TITLE
build: Change eKuiper to version 1.11

### PR DESCRIPTION
**Pull request by lenny-intel**
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-compose/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
run `make run ds-virtual mqtt-broker`
Create eKuiper stream
Create eKuiper rule to post result to MQTT on `result` topic
Use Mqtt.fx to subscribe to `result` topic and verify receiving data

### CODE REVIEW

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@cherrycl , unrelated test failures on this PR. THX!

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cherrycl** [comment]
recheck

**Pull request merged**
