### PR TITLE
fix: Correct get-api-gateway-token.sh script for when DEV env is empty

### PR DESCRIPTION
**Pull request by lenny-intel**
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-compose/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
Run secure stack
Run `make get-token`
Verify no error message, just token displayed.

### CODE REVIEW

**Review by bnevis-i — DISMISSED** [review]

**Comment by lenny-intel** [comment]
@cherrycl , same issue on this simple PR that doesn't have the TAF compose files.

**Comment by cherrycl** [comment]
recheck

**Comment by cherrycl** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Review by bnevis-i — APPROVED** [review]

**Pull request merged**
