### PR TITLE
feat: Enhance mqtt-bus option to include all specified app and device services

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?
Current `mqtt-bus` option only switches the service in the base compose file (core, app-rules, rules-engine) to use MQTT for the MessageBus. Any add on app or device services will still be configured for Redis and have to be modified manually.

## What is the new behavior?
The `mqtt-bus` option now switches all applicable services (core, app-rules, rules-engine, app & device) to use MQTT for the MessageBus. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by cherrycl** [comment]
Got error `./gen_mqtt_messagebus_compose_ext.sh: Permission denied` when executing `make gen` command.

After changing permission for the above file manually, executed `make gen no-secty mqtt-bus ds-virtual ds-modbus` again. Only `data`, `device-virtual` and `device-modbus` use mqtt-bus, the others still use Redis message bus.

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
> Got error `./gen_mqtt_messagebus_compose_ext.sh: Permission denied` when executing `make gen` command.

I have fixed this.

**Comment by lenny-intel** [comment]
> After changing permission for the above file manually, executed `make gen no-secty mqtt-bus ds-virtual ds-modbus` again. Only `data`, `device-virtual` and `device-modbus` use mqtt-bus, the others still use Redis message bus.

WHat are the others? I ran same command and all service that use Message bus ( `data`, `device-virtual` , `device-modbus`, `app-service-rules` and `rulesengine` ) chnage to use MQTT. See my attached compose file.
[docker-compose.yml.txt](https://github.com/edgexfoundry/edgex-compose/files/6925310/docker-compose.yml.txt)

**Review by jim-wang-intel — DISMISSED** [review]
LGTM

**Comment by cherrycl** [comment]
@lenny-intel Sorry, I got misunderstanding. I thought the variable `MESSAGEQUEUE_HOST` in all services should be updated to mqtt-broker.

**Comment by cherrycl** [comment]
@lenny-intel I still got the `Permission denied` error on the branch `lenny-intel:full-mqtt-bus-support`.

**Comment by lenny-intel** [comment]
> I thought the variable `MESSAGEQUEUE_HOST` in all services should be updated to mqtt-broker.

OK, I see what is happening. `MESSAGEQUEUE_HOST` is added to service that do not user it and not overridden by the switch to MQTT. This is because it is in the `common.env` file. I will clean that up so it only appears on the services that actually use it.

**Comment by lenny-intel** [comment]
> @lenny-intel I still got the `Permission denied` error on the branch `lenny-intel:full-mqtt-bus-support`.

That would be because I made the fix on the wrong branch :-( Fix has now been pushed to this branch.

**Comment by lenny-intel** [comment]
> I will clean that up so it only appears on the services that actually use it.

@cherrycl, I have also cleaned up the envs to not add MESSAGEQUEUE_HOST to all services, just those that actually use it.

**Review by cherrycl — APPROVED** [review]
LGTM

**Review by jim-wang-intel — APPROVED** [review]

**Pull request merged**
