### PR TITLE
build: Revert redis 7.2 upgrade (RDB 11 file format)

### PR DESCRIPTION
**Pull request by bnevis-i**
Redis 7.2 has a non-backward compatible RDB file format change.  Reverting.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
recheck

**Comment by bnevis-i** [comment]
recheck

**Comment by bnevis-i** [comment]
recheck

**Comment by bnevis-i** [comment]
recheck

**Comment by lenny-intel** [comment]
@cherrycl , can you help debug this issue?

**Review by lenny-intel — APPROVED** [review]

**Comment by bnevis-i** [comment]
recheck

**Comment by cherrycl** [comment]
@bnevis-i Please rebase this PR and recheck again. The error should be caused by incorrect SHA1 value.

**Comment by bnevis-i** [comment]
@cherrycl Phew!  That did it.  Thank you!

**Pull request merged**
