### PR TITLE
docs: prepare for napa release

### PR DESCRIPTION
**Pull request by bill-mahoney**
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-compose/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Review by lenny-intel — CHANGES_REQUESTED** [review]
There are some README changes needed also.
See changes made for Minnesota hre: https://github.com/edgexfoundry/edgex-compose/pull/382/commits/60fe0b7282396a6aaf981c1109c8caabf7c41a86

**Review by ejlee3 — APPROVED** [review]
LGTM

**Comment by ejlee3** [comment]
> There are some README changes needed also. See changes made for Minnesota hre: [60fe0b7](https://github.com/edgexfoundry/edgex-compose/commit/60fe0b7282396a6aaf981c1109c8caabf7c41a86)

I will do those in a separate PR. can we approve and merge this one and I will fix the Readmes and Jenkinsfile separately?

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
