### PR TITLE
fix: Use correct service key and exe name for ds-snmp

### PR DESCRIPTION
**Pull request by bnevis-i**
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
`make run ds-snmp`

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
recheck

**Comment by bnevis-i** [comment]
image

**Comment by lenny-intel** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
Please rebase this PR

**Pull request merged**
