### PR TITLE
build: Unpin 3rd party images from patch versions

### PR DESCRIPTION
**Pull request by lenny-intel**
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-compose/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Review by bnevis-i — APPROVED** [review]

**Comment by lenny-intel** [comment]
@cherrycl , I assume these smoke test failures are due to the existing TAF failing tests, correct?

**Comment by cherrycl** [comment]
@lenny-intel Yes. I have raised [edgex-go issue #4238](https://github.com/edgexfoundry/edgex-go/issues/4238) for these failures.

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Comment by lenny-intel** [comment]
@cloudxxx8 , looks like the smoke tests are still failing. :-(

**Comment by cloudxxx8** [comment]
the smoke test is currently blocked by https://github.com/edgexfoundry/app-functions-sdk-go/issues/1239

**Comment by lenny-intel** [comment]
> the smoke test is currently blocked by [edgexfoundry/app-functions-sdk-go#1239](https://github.com/edgexfoundry/app-functions-sdk-go/issues/1239)

@cloudxxx8 , ok we have to get all the modules and SDKs updated to be v3 now that the tags are all v3.0.0 based. @ejlee3 is working on getting this done.

**Comment by lenny-intel** [comment]
recheck

**Pull request merged**
