### PR TITLE
feat: Add MessageBus config for all core/support services

### LINKED ISSUE #258: Add MessageBus config for all core/support services
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
 This feature request is MessageBus configuration for base and MQTT Bus

### Description [**REQUIRED**]
With the addition to service metrics the following service will now be utilizing the EdgeX MessageBus and need to have MessageBus configuration overrides in base and for MQTT bus

- Core Metadata
- Core Command
- Support Notifications
- Support Scheduler 

### Describe the solution you'd like
Add MessageQueue to common.env
Update these service to the [add-mqtt-messagebus.yml](https://github.com/edgexfoundry/edgex-compose/blob/main/compose-builder/add-mqtt-messagebus.yml) file with appropriate Env Overrides

### Describe alternatives you've considered
None

### PR DESCRIPTION
**Pull request by lenny-intel**
This is in preparation from when these service's publish Service Metrics or System Events to the MessageBus

closes #258

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-compose/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
Run `make gen no-secty`
Verify all core/support services have the `MESSAGEQUEUE_HOST=edgex-redis` override
Run `make gen no-secty mqtt-bus`
Verify all core/support services have the following env overrides:
- MESSAGEQUEUE_AUTHMODE: none
- MESSAGEQUEUE_HOST: edgex-mqtt-broker
- MESSAGEQUEUE_OPTIONAL_CLIENTID: <service-name>
- MESSAGEQUEUE_PORT: '1883'
- MESSAGEQUEUE_PROTOCOL: tcp
- MESSAGEQUEUE_TYPE: mqtt

### CODE REVIEW

**Review by jim-wang-intel — APPROVED** [review]

**Comment by cloudxxx8** [comment]
recheck

**Review by cloudxxx8 — DISMISSED** [review]
LGTM

**Comment by cloudxxx8** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by cloudxxx8** [comment]
@cherrycl please help check the smoke test when you have time

**Review by jim-wang-intel — DISMISSED** [review]

**Comment by cherrycl** [comment]
recheck

**Comment by cherrycl** [comment]
When triggering the smoke test, TAF always got incorrect `SHA1` value. Not sure if cause by 2 commits. @lenny-intel Could you squash the commits and recheck again?

**Comment by lenny-intel** [comment]
@cherrycl , squashed, but still failing. 
I created this test PR with no real changes and it is passing. https://github.com/edgexfoundry/edgex-compose/pull/262

Think the next step is to recreate this PR.

**Comment by lenny-intel** [comment]
Hum, I rebased an this one passed.

**Review by jim-wang-intel — APPROVED** [review]

**Pull request merged**
