### PR TITLE
fix: Add label:disable to security_opt for SysMgmtAgent

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

SysMgmtAgent gets `permission denied` on CentOS for access to docker

## What is the new behavior?
This resolves permissions issue on CentOS for SysMgmtAgent access to docker

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by bnevis-i — CHANGES_REQUESTED** [review]
Putting a block on the merge until I can regress this on a CentOS box.

**Comment by lenny-intel** [comment]
@bnevis-i , FYI the TAF tests run the Intel tests on CentOS. TAF team has already verified it manually.

**Review by bnevis-i — APPROVED** [review]
Reproduced on SE-Linux enabled Docker installation.

**Pull request merged**
