### PR TITLE
feat: Update to Kuiper version that supports Edgex V2

### PR DESCRIPTION
**Pull request by lenny-intel**
closes 

Signed-off-by: lenny <leonard.goodell@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?
Kuiper 1.1.2-alpine (currently used) and 1.2.0-alpine (new release) do not support Edgex V2

## What is the new behavior?
Using Kuiper 1.2.1-beta.0-alpine which does support Edgex V21

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@cherrycl , @cloudxxx8 , this PR is blocked due to unrelated failing tests. Once you have fixed those tests can you please recheck and merge this PR? THX!

**Comment by cherrycl** [comment]
recheck

**Comment by cloudxxx8** [comment]
@lenny-intel we both don't have the permission to merge PR in this repository

**Comment by lenny-intel** [comment]
>  we both don't have the permission to merge PR in this repository
@cloudxxx8 , @cherrycl , I will get you both added. THX!

**Pull request merged**
