### PR TITLE
build: Update to use Kong 2.5

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?
Currently using Kong 2.4-alpine 

## What is the new behavior?
Now using Kong 2.5 (alpine based image) now that the ARM64 image is available.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by bnevis-i — COMMENTED** [review]
Is scripts/simulator.js supposed to be in this PR?  Isn't referenced anywhere else.

**Comment by lenny-intel** [comment]
> Is scripts/simulator.js supposed to be in this PR? Isn't referenced anywhere else.

No, it should not have been added :-( fixing.

**Comment by lenny-intel** [comment]
@bnevis-i Fixed.

**Review by bnevis-i — APPROVED** [review]
LGTM

**Review by cherrycl — APPROVED** [review]
LGTM

**Pull request merged**
