### PR TITLE
build: Create Ireland released compose files.

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?
Ireland branch has WIP release versions and URLs
READMEs are targeted to WIP release

## What is the new behavior?
Ireland branch will have released versions and URLs
READMEs are targeted to Ireland release

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by bill-mahoney — APPROVED** [review]
LGTM

**Review by ernestojeda — COMMENTED** [review]
Why remove the Jenkinsfile? Would it not be used for 2.0.1 dot release verification for TAF testing?

**Comment by lenny-intel** [comment]
> Why remove the Jenkinsfile? Would it not be used for 2.0.1 dot release verification for TAF testing?

No, the jenkinsfile just runs the TAF smoke tests.  TAF team will manually run the full TAF Functional test suite against any patch releases. 

We could discuss this more in next DevOps to see if we can improve on that process.

**Review by ernestojeda — APPROVED** [review]
LGTM

**Pull request merged**
