### PR TITLE
build: Unpin patch on 3rd party versions and use latest

### PR DESCRIPTION
**Pull request by lenny-intel**
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-compose/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
run `make pull` from top folder
run `make run` from top folder
Verify all service bootstrapped
Change app-rules-engine logging to DEBUG in Consul
Verify logs show events flowing
Test version/ping end point via API gate way.
Verify UI is seeing the following
- 2 device services
- 9 devices
- 9 device profiles

### CODE REVIEW

**Comment by lenny-intel** [comment]
> Reset
> 
> ```
> MOSQUITTO_VERSION=2.0
> NGINX_VERSION=1.25-alpine-slim
> ```

Fixed

**Comment by lenny-intel** [comment]
recheck

**Review by bnevis-i — APPROVED** [review]

**Review by jim-wang-intel — APPROVED** [review]

**Comment by lenny-intel** [comment]
@cherrycl , smoke tests failing to run on this PR. Any ideas? THX!

**Comment by cherrycl** [comment]
@lenny-intel Would you please squash and rebase the commits? TAF can't get correct SHA1 value if PR contains multiple commits.

**Comment by lenny-intel** [comment]
@cherrycl , now all TAF tests are failing. 
I have tried amending commit and force pushing  and even tried recreating the PR (with same commit on new branch)

**Comment by cherrycl** [comment]
recheck

**Comment by cherrycl** [comment]
@lenny-intel Smoke-test job always got incorrect SHA1. Not sure why, but I found this PR's commit seems not synchronize with main branch, could you merge the main branch's commit and try to run the test again?

**Comment by cloudxxx8** [comment]
recheck

**Comment by lenny-intel** [comment]
> @lenny-intel Smoke-test job always got incorrect SHA1. Not sure why, but I found this PR's commit seems not synchronize with main branch, could you merge the main branch's commit and try to run the test again?

@cherrycl , Rebasing fix it. THX!

**Pull request merged**
