### PR TITLE
fix(security): Remove `ENABLE_REGISTRY_ACL` in compose

### PR DESCRIPTION
**Pull request by jim-wang-intel**
- Remove use of feature flag ENABLE_REGISTRY_ACL in compose as it is no longer used

Closes: #89
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

There is left-over flag `ENABLE_REGISTRY_ACL` in compose and should be removed as [`edgex-go` PR](https://github.com/edgexfoundry/edgex-go/pull/3461) is going to remove it.

## What is the new behavior?
No flag `ENABLE_REGISTRY_ACL` used any more.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information
This PR should merge together with edgex-go PR https://github.com/edgexfoundry/edgex-go/pull/3461

### CODE REVIEW

**Review by beaufrusetta — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Pull request merged**
