### PR TITLE
feat: Adjust Device MQTT extension compose for V2 custom config

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?
Env override was for V1 version's config

## What is the new behavior?
Env overrides are now for new V2 config
ProfilesDir and DevicesDir also set via overrides

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by cherrycl** [comment]
recheck

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
Holding on merge until PR (https://github.com/edgexfoundry/device-mqtt-go/pull/288) on Device MQTT is completed and merged, so these changes can be validated once more.

**Comment by lenny-intel** [comment]
recheck

**Pull request merged**
